// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOPLP_API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NOPLP_API.Migrations
{
    [DbContext(typeof(NoplpDbContext))]
    partial class NoplpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NOPLP_API.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("NOPLP_API.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<bool>("MemeChanson")
                        .HasColumnType("boolean")
                        .HasColumnName("meme_chanson");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("NOPLP_API.Entities.SongTheme", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid")
                        .HasColumnName("song_id");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uuid");

                    b.HasKey("SongId", "ThemeId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ThemeId");

                    b.ToTable("songs_themes", (string)null);
                });

            modelBuilder.Entity("NOPLP_API.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("NOPLP_API.Entities.Song", b =>
                {
                    b.HasOne("NOPLP_API.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("NOPLP_API.Entities.SongTheme", b =>
                {
                    b.HasOne("NOPLP_API.Entities.Artist", null)
                        .WithMany("SongThemes")
                        .HasForeignKey("ArtistId");

                    b.HasOne("NOPLP_API.Entities.Song", "Song")
                        .WithMany("SongThemes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NOPLP_API.Entities.Theme", "Theme")
                        .WithMany("SongThemes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("NOPLP_API.Entities.Artist", b =>
                {
                    b.Navigation("SongThemes");
                });

            modelBuilder.Entity("NOPLP_API.Entities.Song", b =>
                {
                    b.Navigation("SongThemes");
                });

            modelBuilder.Entity("NOPLP_API.Entities.Theme", b =>
                {
                    b.Navigation("SongThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
